### ISSUE TITLE
Example is not working.

### ISSUE THREAD

**Issue by andras-gyarmati** [mateo2181/vue-swappable#1]
Hi! I was really happy that someone implemented the swap functionality, but unfortunately the example that you provided did not work for me. Can you please provide a working example like the ones in the draggable repo?

related issue in draggable: https://github.com/SortableJS/Vue.Draggable/issues/466

draggable is working for me like this:
```
<tamplate>
...
  <draggable class="row" v-model="data.words" @start="drag=true" @end="drag=false">
    <b-col v-for="word in data.words" :key="word.key">
      <b-button class="btn-sm btn-block">{{ word.value }}</b-button>
    </b-col>
  </draggable>
...
</template>

<script>
import draggable from "vuedraggable";
...
</script>
```

**Comment by mateo2181** [comment]
@andras-gyarmati you can clone this repo and run the example I did here. Then you can customize it as you want.
